name: tianrui
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - networkx
  - tqdm
  - pyyaml
  - pytorch-lightning
  - optuna
  - matplotlib
